print("Hello from Session 2")
print("Hello from Student A") 
print("Hello from Student B")

print("I'm doing great, thank you!")
print("I'm doing great, thank you!")
print("Hello from Student A")
print("I'm doing great, thank you!")
print("I'm doing great, thank you!")
print("Hello from Student A")
